// <auto-generated />
using System;
using BusinessSearcher.Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessSearcher.Infrastructure.Persistence.Migrations.Radar
{
    [DbContext(typeof(RadarDbContext))]
    [Migration("20260731180044_AddClientLocation")]
    partial class AddClientLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.AvailabilityAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_triggered_at");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("max_price");

                    b.Property<string>("NormalizedProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_product_name");

                    b.Property<string>("ProductNameFilter")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name_filter");

                    b.Property<double?>("RadiusKm")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_km");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_availability_alerts");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_availability_alerts_client_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_availability_alerts_is_active");

                    b.ToTable("availability_alerts", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.AvailabilityReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("Municipality")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("municipality");

                    b.Property<string>("NormalizedProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_product_name");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("place_name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<string>("QueueStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("queue_status");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<Guid>("ReporterClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_client_id");

                    b.Property<int>("ReporterReputationSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("reporter_reputation_snapshot");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_availability_reports");

                    b.HasIndex("City")
                        .HasDatabaseName("ix_availability_reports_city");

                    b.HasIndex("NormalizedProductName")
                        .HasDatabaseName("ix_availability_reports_normalized_product_name");

                    b.HasIndex("ReportedAt")
                        .HasDatabaseName("ix_availability_reports_reported_at");

                    b.ToTable("availability_reports", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<int>("ConfirmationsReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("confirmations_received");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fcm_token");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plan");

                    b.Property<DateTime?>("PremiumUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("premium_until");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("referral_code");

                    b.Property<int>("ReferralMonthAnchor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("referral_month_anchor");

                    b.Property<Guid?>("ReferredByClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("referred_by_client_id");

                    b.Property<int>("ReportsSubmitted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reports_submitted");

                    b.Property<int>("ReputationScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50)
                        .HasColumnName("reputation_score");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ValidReferralsThisMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("valid_referrals_this_month");

                    b.Property<int>("ValidReferralsTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("valid_referrals_total");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("ReferralCode")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_referral_code");

                    b.ToTable("clients", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.ClientProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_client_products");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_products_client_id");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("ix_client_products_is_available");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_client_products_normalized_name");

                    b.ToTable("client_products", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.CommunityAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswererName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("answerer_name");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_community_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_community_answers_question_id");

                    b.ToTable("community_answers", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.CommunityQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AskerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("asker_name");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ProductName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_community_questions");

                    b.HasIndex("City")
                        .HasDatabaseName("ix_community_questions_city");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_community_questions_created_at");

                    b.ToTable("community_questions", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InvitedClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_client_id");

                    b.Property<Guid>("InviterClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("inviter_client_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.HasKey("Id")
                        .HasName("pk_referrals");

                    b.HasIndex("InvitedClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_referrals_invited_client_id");

                    b.HasIndex("InviterClientId")
                        .HasDatabaseName("ix_referrals_inviter_client_id");

                    b.ToTable("referrals", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Entities.ClientEmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_client_email_verification_tokens");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_email_verification_tokens_client_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_client_email_verification_tokens_token");

                    b.ToTable("client_email_verification_tokens", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Entities.ClientPasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_client_password_reset_tokens");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_password_reset_tokens_client_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_client_password_reset_tokens_token");

                    b.ToTable("client_password_reset_tokens", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Entities.ClientRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_client_refresh_tokens");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_client_refresh_tokens_client_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_client_refresh_tokens_token");

                    b.ToTable("client_refresh_tokens", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Entities.ReportConfirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Agrees")
                        .HasColumnType("boolean")
                        .HasColumnName("agrees");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("ReportedStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reported_status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_report_confirmations");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_report_confirmations_report_id");

                    b.HasIndex("ReportId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_report_confirmations_report_id_client_id");

                    b.ToTable("report_confirmations", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.AvailabilityAlert", b =>
                {
                    b.OwnsOne("BusinessSearcher.Domain.BoundedContext.Radar.ValueObjects.GeoLocation", "Center", b1 =>
                        {
                            b1.Property<Guid>("AvailabilityAlertId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("center_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("center_longitude");

                            b1.HasKey("AvailabilityAlertId");

                            b1.ToTable("availability_alerts", "public");

                            b1.WithOwner()
                                .HasForeignKey("AvailabilityAlertId")
                                .HasConstraintName("fk_availability_alerts_availability_alerts_id");
                        });

                    b.Navigation("Center");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.AvailabilityReport", b =>
                {
                    b.OwnsOne("BusinessSearcher.Domain.BoundedContext.Radar.ValueObjects.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("AvailabilityReportId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("AvailabilityReportId");

                            b1.ToTable("availability_reports", "public");

                            b1.WithOwner()
                                .HasForeignKey("AvailabilityReportId")
                                .HasConstraintName("fk_availability_reports_availability_reports_id");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.Client", b =>
                {
                    b.OwnsOne("BusinessSearcher.Domain.BoundedContext.TenantManagement.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("email");

                            b1.HasKey("ClientId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_clients_email");

                            b1.ToTable("clients", "public");

                            b1.WithOwner()
                                .HasForeignKey("ClientId")
                                .HasConstraintName("fk_clients_clients_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.CommunityAnswer", b =>
                {
                    b.HasOne("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.CommunityQuestion", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_community_answers_community_questions_question_id");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Entities.ClientEmailVerificationToken", b =>
                {
                    b.HasOne("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.Client", null)
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_email_verification_tokens_clients_client_id");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Entities.ClientPasswordResetToken", b =>
                {
                    b.HasOne("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.Client", null)
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_password_reset_tokens_clients_client_id");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Entities.ClientRefreshToken", b =>
                {
                    b.HasOne("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.Client", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_refresh_tokens_clients_client_id");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Entities.ReportConfirmation", b =>
                {
                    b.HasOne("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.AvailabilityReport", null)
                        .WithMany("Confirmations")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_confirmations_availability_reports_report_id");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.AvailabilityReport", b =>
                {
                    b.Navigation("Confirmations");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.Client", b =>
                {
                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Radar.Aggregates.CommunityQuestion", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
