// <auto-generated />
using System;
using BusinessSearcher.Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessSearcher.Infrastructure.Persistence.Migrations.Operations
{
    [DbContext(typeof(OperationsDbContext))]
    [Migration("20261007094852_AddManagersAndObservador_Operations")]
    partial class AddManagersAndObservador_Operations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("details");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Method")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("method");

                    b.Property<string>("Path")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TargetEntity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_entity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserRole")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("user_role");

                    b.HasKey("Id")
                        .HasName("pk_op_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_op_audit_logs_user_id");

                    b.HasIndex("TenantId", "Timestamp")
                        .HasDatabaseName("ix_op_audit_logs_tenant_id_timestamp");

                    b.ToTable("op_audit_logs", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.BusinessInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("phone");

                    b.Property<string>("TaxId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tax_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_op_business_info");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_op_business_info_tenant_id");

                    b.ToTable("op_business_info", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.CashMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("AmountUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("RegisterId")
                        .HasColumnType("uuid")
                        .HasColumnName("register_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_op_cash_movements");

                    b.HasIndex("TenantId", "RegisterId")
                        .HasDatabaseName("ix_op_cash_movements_tenant_id_register_id");

                    b.ToTable("op_cash_movements", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.CashRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("actual_amount");

                    b.Property<decimal?>("ActualAmountUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("actual_amount_usd");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("close_date");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Difference")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("difference");

                    b.Property<decimal?>("DifferenceUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("difference_usd");

                    b.Property<decimal?>("ExpectedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("expected_amount");

                    b.Property<decimal?>("ExpectedAmountUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("expected_amount_usd");

                    b.Property<decimal>("InitialAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("initial_amount");

                    b.Property<decimal?>("InitialAmountUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("initial_amount_usd");

                    b.Property<bool>("InventoryCountCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("inventory_count_completed");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_date");

                    b.Property<Guid>("OpenedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by");

                    b.Property<int>("SalesCount")
                        .HasColumnType("integer")
                        .HasColumnName("sales_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("terminal_id");

                    b.Property<decimal>("TotalCashIn")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_cash_in");

                    b.Property<decimal>("TotalCashOut")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_cash_out");

                    b.Property<decimal>("TotalExpenses")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_expenses");

                    b.Property<decimal>("TotalSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_sales");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_op_cash_registers");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_op_cash_registers_tenant_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_op_cash_registers_tenant_id_status");

                    b.ToTable("op_cash_registers", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.CatalogImport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("CatalogDate")
                        .HasColumnType("date")
                        .HasColumnName("catalog_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid?>("ImportedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("imported_by");

                    b.Property<int>("ProductCount")
                        .HasColumnType("integer")
                        .HasColumnName("product_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_op_catalog_imports");

                    b.HasIndex("TenantId", "WarehouseId", "CatalogDate")
                        .IsUnique()
                        .HasDatabaseName("ix_op_catalog_imports_tenant_id_warehouse_id_catalog_date");

                    b.ToTable("op_catalog_imports", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_op_categories");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_op_categories_tenant_id");

                    b.ToTable("op_categories", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.ExchangeRateLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("rate");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_op_exchange_rates");

                    b.HasIndex("TenantId", "Date")
                        .HasDatabaseName("ix_op_exchange_rates_tenant_id_date");

                    b.ToTable("op_exchange_rates", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("AmountUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("RegisterId")
                        .HasColumnType("uuid")
                        .HasColumnName("register_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_op_expenses");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_op_expenses_date");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_op_expenses_tenant_id");

                    b.ToTable("op_expenses", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.InventoryCount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Adjusted")
                        .HasColumnType("boolean")
                        .HasColumnName("adjusted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_op_inventory_counts");

                    b.HasIndex("TenantId", "WarehouseId")
                        .HasDatabaseName("ix_op_inventory_counts_tenant_id_warehouse_id");

                    b.ToTable("op_inventory_counts", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.InventoryCountItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Audited")
                        .HasColumnType("boolean")
                        .HasColumnName("audited");

                    b.Property<int>("CountedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("counted_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InventoryCountId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_count_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("SystemQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("system_quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_op_inventory_count_items");

                    b.HasIndex("InventoryCountId")
                        .HasDatabaseName("ix_op_inventory_count_items_inventory_count_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_op_inventory_count_items_product_id");

                    b.ToTable("op_inventory_count_items", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid?>("FromWarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_warehouse_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("ToWarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_warehouse_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_op_inventory_movements");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_op_inventory_movements_product_id");

                    b.HasIndex("TenantId", "Date")
                        .HasDatabaseName("ix_op_inventory_movements_tenant_id_date");

                    b.ToTable("op_inventory_movements", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id_number");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("municipality");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_op_managers");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_op_managers_tenant_id_code");

                    b.ToTable("op_managers", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.OperationsUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedRegisterId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_register_id");

                    b.Property<Guid?>("AssignedWarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_warehouse_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_op_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_op_users_email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_op_users_tenant_id");

                    b.ToTable("op_users", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("barcode");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("batch_number");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cost_price");

                    b.Property<decimal?>("CostPriceUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cost_price_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<bool>("ForSale")
                        .HasColumnType("boolean")
                        .HasColumnName("for_sale");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPubliclyVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_publicly_visible");

                    b.Property<int>("MinOrderQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("min_order_quantity");

                    b.Property<int>("MinStock")
                        .HasColumnType("integer")
                        .HasColumnName("min_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sell_price");

                    b.Property<decimal?>("SellPriceUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sell_price_usd");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("tax_rate");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_op_products");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_op_products_tenant_id");

                    b.HasIndex("TenantId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_op_products_tenant_id_barcode")
                        .HasFilter("is_active AND barcode IS NOT NULL");

                    b.HasIndex("IsPubliclyVisible", "ForSale", "IsActive")
                        .HasDatabaseName("ix_op_products_is_publicly_visible_for_sale_is_active");

                    b.ToTable("op_products", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.ProductPriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("change_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("NewCostPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("new_cost_price");

                    b.Property<decimal?>("NewCostPriceUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("new_cost_price_usd");

                    b.Property<decimal>("NewSellPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("new_sell_price");

                    b.Property<decimal?>("NewSellPriceUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("new_sell_price_usd");

                    b.Property<decimal>("OldCostPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("old_cost_price");

                    b.Property<decimal?>("OldCostPriceUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("old_cost_price_usd");

                    b.Property<decimal>("OldSellPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("old_sell_price");

                    b.Property<decimal?>("OldSellPriceUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("old_sell_price_usd");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_op_product_price_history");

                    b.HasIndex("TenantId", "ProductId")
                        .HasDatabaseName("ix_op_product_price_history_tenant_id_product_id");

                    b.ToTable("op_product_price_history", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.ProductStock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AverageCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("average_cost");

                    b.Property<decimal?>("AverageCostUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("average_cost_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("SellPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sell_price");

                    b.Property<decimal?>("SellPriceUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sell_price_usd");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_op_product_stocks");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_op_product_stocks_warehouse_id");

                    b.HasIndex("ProductId", "WarehouseId")
                        .IsUnique()
                        .HasDatabaseName("ix_op_product_stocks_product_id_warehouse_id");

                    b.ToTable("op_product_stocks", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AssociatedExpenses")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("associated_expenses");

                    b.Property<decimal?>("AssociatedExpensesUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("associated_expenses_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("exchange_rate");

                    b.Property<string>("InvoiceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("invoice_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal?>("TotalUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_usd");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<string>("_purchaseRequestIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("purchase_request_ids");

                    b.HasKey("Id")
                        .HasName("pk_op_purchases");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_op_purchases_tenant_id");

                    b.HasIndex("TenantId", "Date")
                        .HasDatabaseName("ix_op_purchases_tenant_id_date");

                    b.ToTable("op_purchases", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.PurchaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("batch_number");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cost_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_op_purchase_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_op_purchase_items_product_id");

                    b.HasIndex("PurchaseId")
                        .HasDatabaseName("ix_op_purchase_items_purchase_id");

                    b.ToTable("op_purchase_items", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.PurchaseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("integer")
                        .HasColumnName("current_stock");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("MinStock")
                        .HasColumnType("integer")
                        .HasColumnName("min_stock");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("requested_quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_op_purchase_requests");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_op_purchase_requests_tenant_id_status");

                    b.ToTable("op_purchase_requests", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.RoleSalaryConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_salary");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<decimal>("SalesPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("sales_percentage");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_op_role_salary_configs");

                    b.HasIndex("TenantId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_op_role_salary_configs_tenant_id_role");

                    b.ToTable("op_role_salary_configs", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uuid")
                        .HasColumnName("cashier_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("exchange_rate");

                    b.Property<string>("ManagerCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("manager_code");

                    b.Property<string>("PaymentCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("payment_currency");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_method");

                    b.Property<Guid>("RegisterId")
                        .HasColumnType("uuid")
                        .HasColumnName("register_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal?>("SubtotalUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal_usd");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TerminalName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("terminal_name");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal?>("TotalUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_usd");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_op_sales");

                    b.HasIndex("RegisterId")
                        .HasDatabaseName("ix_op_sales_register_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_op_sales_tenant_id");

                    b.HasIndex("TenantId", "Date")
                        .HasDatabaseName("ix_op_sales_tenant_id_date");

                    b.ToTable("op_sales", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_value");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_op_sale_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_op_sale_items_product_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_op_sale_items_sale_id");

                    b.ToTable("op_sale_items", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.SalePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("AmountUSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_usd");

                    b.Property<decimal?>("CashTendered")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cash_tendered");

                    b.Property<decimal?>("Change")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("change");

                    b.Property<string>("ChangeCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("change_currency");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_op_sale_payments");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_op_sale_payments_sale_id");

                    b.ToTable("op_sale_payments", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_op_settings");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_op_settings_tenant_id_key");

                    b.ToTable("op_settings", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("address");

                    b.Property<string>("Category")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("category");

                    b.Property<string>("Contact")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contact");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("phone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_op_suppliers");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_op_suppliers_tenant_id");

                    b.ToTable("op_suppliers", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Terminal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_op_terminals");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_op_terminals_tenant_id");

                    b.ToTable("op_terminals", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_op_warehouses");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_op_warehouses_tenant_id");

                    b.ToTable("op_warehouses", "public");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.InventoryCountItem", b =>
                {
                    b.HasOne("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.InventoryCount", null)
                        .WithMany("Items")
                        .HasForeignKey("InventoryCountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_op_inventory_count_items_op_inventory_counts_inventory_coun");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.ProductStock", b =>
                {
                    b.HasOne("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Product", null)
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_op_product_stocks_op_products_product_id");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.PurchaseItem", b =>
                {
                    b.HasOne("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Purchase", null)
                        .WithMany("Items")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_op_purchase_items_op_purchases_purchase_id");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.SaleItem", b =>
                {
                    b.HasOne("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Sale", null)
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_op_sale_items_op_sales_sale_id");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.SalePayment", b =>
                {
                    b.HasOne("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Sale", null)
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_op_sale_payments_op_sales_sale_id");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.InventoryCount", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Product", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Purchase", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BusinessSearcher.Domain.BoundedContext.Operations.Aggregates.Sale", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
